psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD '$REPLICATOR_PASSWORD';
    SELECT * FROM pg_create_physical_replication_slot('$REPLICATION_SLOT_NAME');
EOSQL
